### ISSUE TITLE
Experiment with navbar solutions for desktop and mobile

### ISSUE THREAD

**Issue by ekressmiller** [mplp/docassemble-Simpmotion#40]
Trying to come up with a way to display detailed section info on larger screens but just a review link on smaller screens.

**Comment by ekressmiller** [comment]
if we add something like this to mlh_framework_theme.css:

/* Hide the "right" screen part when screen is larger enough to display nav panel on left */
@media (min-width: 768px) {
  #daright {
    display: none !important;
  }
  #darightbottom {
    display: none !important;
  }
}

We can make the right screen part not appear when screen is small. That way we can do something like this:

When screen is big, use the full nav panel with a review link:
![image](https://github.com/mplp/docassemble-Simpmotion/assets/110936328/0ddaecc7-090a-474b-bb1f-f328e42f43a5)
When screen is small, use screen part link at bottom of page instead:
![image](https://github.com/mplp/docassemble-Simpmotion/assets/110936328/4de8428b-9388-46bb-83bb-5fe61bb74ea8)
When **logged out:** (would want to fine-tune appearance a bit)
desktop small:
![image](https://github.com/mplp/docassemble-Simpmotion/assets/110936328/ab5a1e64-4bdc-42d3-86ca-82bee1cea2c7)
iphone:
![IMG_2690 smaller](https://github.com/mplp/docassemble-Simpmotion/assets/110936328/f660d491-f8b6-4607-a2c3-636755eb9587)

**Comment by ekressmiller** [comment]
Need to decide whether also want progress bar or not. (I don't know if that's customizable between smaller and large screens-I don't see a built-in way to customize it.)  And could also work in intermittent "Road Map" screens to orient people.

**Comment by ekressmiller** [comment]
@BryceStevenWilley This is an idea for how we can have the nave panel section info on larger screens but just a review link on small screens. Can you take a look when you have a moment and see if you see any red flags or ways to do it better?

I'm also interested in how to mess with the formatting so it looks as good as possible on small screens when someone is logged out.

**Comment by ekressmiller** [comment]
@RamiLorca @normon66 
Here's my most recent nav panel design idea with pics and code. We can discuss at the meeting or let me know if you have thoughts!

**Comment by BryceStevenWilley** [comment]
I can definitely take a look this weekend! I'll post my thoughts (and any code I write) here.

**Comment by BryceStevenWilley** [comment]
IMO, it works really great! As is, the only thing that I think would need to change is the font color of the review sections; now that the only section that's actually a link is the "Edit answers", the other sections having the same font color is a little confusing, even with the extra underline on "Edit answers". Changing that to a normal black would be good: this CSS should work (this is something that could be added to AssemblyLine upstream, IMO):

```css
/* get all of the navigation links that aren't clickable */
.danavdiv a:not(.daclickable) {
  color: var(--bs-body-color);
}
```

That said, an alternative approach I think could also work is to edit the `default screen parts: under`, instead of right, and simply always show the "Edit answers" link there, whether or not they're logged in, or if it's mobile or not. This is the YAML block I added to `simpmotion.yml`:

```
default screen parts:
  under: |
    ✎ [Edit Answers](${ url_action('review_simpmotion') })

    % if not user_logged_in():
    [:key: Sign in](${url_of('login', next=interview_url())}) or [sign up](${url_of('register', next=interview_url())}) to save your progress.
    % endif
```

Both would be fine, using `under` has less CSS that requires you to hide things.

 Some screenshots below:

* logged in desktop: 
![Screenshot from 2024-02-24 16-50-45](https://github.com/mplp/docassemble-Simpmotion/assets/6252212/1abb0e3e-ca8a-42d0-9e1c-bb02cbfbe1cf)
* logged in mobile: 
![Screenshot from 2024-02-24 16-51-07](https://github.com/mplp/docassemble-Simpmotion/assets/6252212/bb3ffb62-ca00-4fc6-b874-31dcc2c08ce9)
* no account desktop: 
![Screenshot from 2024-02-24 16-51-32](https://github.com/mplp/docassemble-Simpmotion/assets/6252212/1df857ec-5ac9-4697-827e-45570cedd957)

**Comment by ekressmiller** [comment]
Thanks Bryce! Oh yeah that's a good idea, I gave up on Under when I realized that the "sign in or sign up" stuff was in there, not even thinking they could both go there!

For the team to see how it looks, here's Bryce's idea on desktop logged in with a nav panel:
![image](https://github.com/mplp/docassemble-Simpmotion/assets/110936328/1e66e992-f965-4c06-bb66-db1a7e5f8b84)
On desktop logged out with a nav panel:
![image](https://github.com/mplp/docassemble-Simpmotion/assets/110936328/eeb42480-2094-4f04-b045-fc0cd9e28d7c)

**Comment by normon66** [comment]
I think that using the `under` section is a great idea! If we decide to put that in the framework, we'll just need to have a consistent name for the main review screen, e.g.:

```
default screen parts:
  under: |
    ✎ [Edit Answers](${ url_action('review_master') })
```

**Comment by ekressmiller** [comment]
I'm soliciting feedback from the MLH team on whether they prefer putting the link in the nav panel or under the buttons on desktop.

**Comment by ekressmiller** [comment]
Team preferred link in nav panel on larger screens. Finalized framework pull request and requested review from Brett. 

[Documentation here](https://docs.google.com/document/d/1gzNbt_S5k6hcKNxq-lFtQF0iEnm0h5K7vXv7ABrgQbc/edit#heading=h.otzf402o5fu5) for how to implement this in each individual interview.

Note: we will want to come up with some code to include in each review screen so that it's not just empty at the beginning of the interview. Maybe to display something like "Your answers will start to show up here once you finish the Introduction section." and then hide that text once we actually have answers on the review screen.
